// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeat.proto

package com.ycj.imv3.entity;

public final class HeartbeatOuterClass {
  private HeartbeatOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeartbeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.imv3.Heartbeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 uid = 1;</code>
     * @return The uid.
     */
    long getUid();

    /**
     * <code>int32 state = 2;</code>
     * @return The state.
     */
    int getState();

    /**
     * <code>optional double loca1 = 3;</code>
     * @return Whether the loca1 field is set.
     */
    boolean hasLoca1();
    /**
     * <code>optional double loca1 = 3;</code>
     * @return The loca1.
     */
    double getLoca1();

    /**
     * <code>optional double loca2 = 4;</code>
     * @return Whether the loca2 field is set.
     */
    boolean hasLoca2();
    /**
     * <code>optional double loca2 = 4;</code>
     * @return The loca2.
     */
    double getLoca2();

    /**
     * <code>optional string location = 5;</code>
     * @return Whether the location field is set.
     */
    boolean hasLocation();
    /**
     * <code>optional string location = 5;</code>
     * @return The location.
     */
    String getLocation();
    /**
     * <code>optional string location = 5;</code>
     * @return The bytes for location.
     */
    com.google.protobuf.ByteString
        getLocationBytes();
  }
  /**
   * Protobuf type {@code com.imv3.Heartbeat}
   */
  public static final class Heartbeat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.imv3.Heartbeat)
      HeartbeatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Heartbeat.newBuilder() to construct.
    private Heartbeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Heartbeat() {
      location_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Heartbeat();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Heartbeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              uid_ = input.readInt64();
              break;
            }
            case 16: {

              state_ = input.readInt32();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000001;
              loca1_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000002;
              loca2_ = input.readDouble();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              location_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HeartbeatOuterClass.internal_static_com_imv3_Heartbeat_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HeartbeatOuterClass.internal_static_com_imv3_Heartbeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Heartbeat.class, Builder.class);
    }

    private int bitField0_;
    public static final int UID_FIELD_NUMBER = 1;
    private long uid_;
    /**
     * <code>int64 uid = 1;</code>
     * @return The uid.
     */
    @Override
    public long getUid() {
      return uid_;
    }

    public static final int STATE_FIELD_NUMBER = 2;
    private int state_;
    /**
     * <code>int32 state = 2;</code>
     * @return The state.
     */
    @Override
    public int getState() {
      return state_;
    }

    public static final int LOCA1_FIELD_NUMBER = 3;
    private double loca1_;
    /**
     * <code>optional double loca1 = 3;</code>
     * @return Whether the loca1 field is set.
     */
    @Override
    public boolean hasLoca1() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional double loca1 = 3;</code>
     * @return The loca1.
     */
    @Override
    public double getLoca1() {
      return loca1_;
    }

    public static final int LOCA2_FIELD_NUMBER = 4;
    private double loca2_;
    /**
     * <code>optional double loca2 = 4;</code>
     * @return Whether the loca2 field is set.
     */
    @Override
    public boolean hasLoca2() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional double loca2 = 4;</code>
     * @return The loca2.
     */
    @Override
    public double getLoca2() {
      return loca2_;
    }

    public static final int LOCATION_FIELD_NUMBER = 5;
    private volatile Object location_;
    /**
     * <code>optional string location = 5;</code>
     * @return Whether the location field is set.
     */
    @Override
    public boolean hasLocation() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string location = 5;</code>
     * @return The location.
     */
    @Override
    public String getLocation() {
      Object ref = location_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        location_ = s;
        return s;
      }
    }
    /**
     * <code>optional string location = 5;</code>
     * @return The bytes for location.
     */
    @Override
    public com.google.protobuf.ByteString
        getLocationBytes() {
      Object ref = location_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        location_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0L) {
        output.writeInt64(1, uid_);
      }
      if (state_ != 0) {
        output.writeInt32(2, state_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeDouble(3, loca1_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeDouble(4, loca2_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, location_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uid_);
      }
      if (state_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, state_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, loca1_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, loca2_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, location_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Heartbeat)) {
        return super.equals(obj);
      }
      Heartbeat other = (Heartbeat) obj;

      if (getUid()
          != other.getUid()) return false;
      if (getState()
          != other.getState()) return false;
      if (hasLoca1() != other.hasLoca1()) return false;
      if (hasLoca1()) {
        if (Double.doubleToLongBits(getLoca1())
            != Double.doubleToLongBits(
                other.getLoca1())) return false;
      }
      if (hasLoca2() != other.hasLoca2()) return false;
      if (hasLoca2()) {
        if (Double.doubleToLongBits(getLoca2())
            != Double.doubleToLongBits(
                other.getLoca2())) return false;
      }
      if (hasLocation() != other.hasLocation()) return false;
      if (hasLocation()) {
        if (!getLocation()
            .equals(other.getLocation())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUid());
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState();
      if (hasLoca1()) {
        hash = (37 * hash) + LOCA1_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            Double.doubleToLongBits(getLoca1()));
      }
      if (hasLoca2()) {
        hash = (37 * hash) + LOCA2_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            Double.doubleToLongBits(getLoca2()));
      }
      if (hasLocation()) {
        hash = (37 * hash) + LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getLocation().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Heartbeat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Heartbeat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Heartbeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Heartbeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Heartbeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Heartbeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Heartbeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Heartbeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Heartbeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Heartbeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Heartbeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Heartbeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Heartbeat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.imv3.Heartbeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.imv3.Heartbeat)
        HeartbeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HeartbeatOuterClass.internal_static_com_imv3_Heartbeat_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HeartbeatOuterClass.internal_static_com_imv3_Heartbeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Heartbeat.class, Builder.class);
      }

      // Construct using com.ycj.imv3.entity.HeartbeatOuterClass.Heartbeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        uid_ = 0L;

        state_ = 0;

        loca1_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        loca2_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        location_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HeartbeatOuterClass.internal_static_com_imv3_Heartbeat_descriptor;
      }

      @Override
      public Heartbeat getDefaultInstanceForType() {
        return Heartbeat.getDefaultInstance();
      }

      @Override
      public Heartbeat build() {
        Heartbeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Heartbeat buildPartial() {
        Heartbeat result = new Heartbeat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.uid_ = uid_;
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.loca1_ = loca1_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.loca2_ = loca2_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.location_ = location_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Heartbeat) {
          return mergeFrom((Heartbeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Heartbeat other) {
        if (other == Heartbeat.getDefaultInstance()) return this;
        if (other.getUid() != 0L) {
          setUid(other.getUid());
        }
        if (other.getState() != 0) {
          setState(other.getState());
        }
        if (other.hasLoca1()) {
          setLoca1(other.getLoca1());
        }
        if (other.hasLoca2()) {
          setLoca2(other.getLoca2());
        }
        if (other.hasLocation()) {
          bitField0_ |= 0x00000004;
          location_ = other.location_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Heartbeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Heartbeat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long uid_ ;
      /**
       * <code>int64 uid = 1;</code>
       * @return The uid.
       */
      @Override
      public long getUid() {
        return uid_;
      }
      /**
       * <code>int64 uid = 1;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(long value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 uid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        
        uid_ = 0L;
        onChanged();
        return this;
      }

      private int state_ ;
      /**
       * <code>int32 state = 2;</code>
       * @return The state.
       */
      @Override
      public int getState() {
        return state_;
      }
      /**
       * <code>int32 state = 2;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(int value) {
        
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 state = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }

      private double loca1_ ;
      /**
       * <code>optional double loca1 = 3;</code>
       * @return Whether the loca1 field is set.
       */
      @Override
      public boolean hasLoca1() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional double loca1 = 3;</code>
       * @return The loca1.
       */
      @Override
      public double getLoca1() {
        return loca1_;
      }
      /**
       * <code>optional double loca1 = 3;</code>
       * @param value The loca1 to set.
       * @return This builder for chaining.
       */
      public Builder setLoca1(double value) {
        bitField0_ |= 0x00000001;
        loca1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double loca1 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLoca1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        loca1_ = 0D;
        onChanged();
        return this;
      }

      private double loca2_ ;
      /**
       * <code>optional double loca2 = 4;</code>
       * @return Whether the loca2 field is set.
       */
      @Override
      public boolean hasLoca2() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional double loca2 = 4;</code>
       * @return The loca2.
       */
      @Override
      public double getLoca2() {
        return loca2_;
      }
      /**
       * <code>optional double loca2 = 4;</code>
       * @param value The loca2 to set.
       * @return This builder for chaining.
       */
      public Builder setLoca2(double value) {
        bitField0_ |= 0x00000002;
        loca2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double loca2 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLoca2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        loca2_ = 0D;
        onChanged();
        return this;
      }

      private Object location_ = "";
      /**
       * <code>optional string location = 5;</code>
       * @return Whether the location field is set.
       */
      public boolean hasLocation() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string location = 5;</code>
       * @return The location.
       */
      public String getLocation() {
        Object ref = location_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          location_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string location = 5;</code>
       * @return The bytes for location.
       */
      public com.google.protobuf.ByteString
          getLocationBytes() {
        Object ref = location_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          location_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string location = 5;</code>
       * @param value The location to set.
       * @return This builder for chaining.
       */
      public Builder setLocation(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        location_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string location = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocation() {
        bitField0_ = (bitField0_ & ~0x00000004);
        location_ = getDefaultInstance().getLocation();
        onChanged();
        return this;
      }
      /**
       * <code>optional string location = 5;</code>
       * @param value The bytes for location to set.
       * @return This builder for chaining.
       */
      public Builder setLocationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000004;
        location_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.imv3.Heartbeat)
    }

    // @@protoc_insertion_point(class_scope:com.imv3.Heartbeat)
    private static final Heartbeat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Heartbeat();
    }

    public static Heartbeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Heartbeat>
        PARSER = new com.google.protobuf.AbstractParser<Heartbeat>() {
      @Override
      public Heartbeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Heartbeat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Heartbeat> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Heartbeat> getParserForType() {
      return PARSER;
    }

    @Override
    public Heartbeat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_imv3_Heartbeat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_imv3_Heartbeat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017heartbeat.proto\022\010com.imv3\"\207\001\n\tHeartbea" +
      "t\022\013\n\003uid\030\001 \001(\003\022\r\n\005state\030\002 \001(\005\022\022\n\005loca1\030\003" +
      " \001(\001H\000\210\001\001\022\022\n\005loca2\030\004 \001(\001H\001\210\001\001\022\025\n\010locatio" +
      "n\030\005 \001(\tH\002\210\001\001B\010\n\006_loca1B\010\n\006_loca2B\013\n\t_loc" +
      "ationB\027\n\023com.ycj.imv3.entityP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_imv3_Heartbeat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_imv3_Heartbeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_imv3_Heartbeat_descriptor,
        new String[] { "Uid", "State", "Loca1", "Loca2", "Location", "Loca1", "Loca2", "Location", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
